"""add token growth and momentum intelligence

Revision ID: 0886562e408b
Revises: f9142beb610b
Create Date: 2026-06-20 12:55:55.337513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0886562e408b'
down_revision: Union[str, None] = 'f9142beb610b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('momentum_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('price_change_1h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price_change_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price_change_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price_change_30d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volatility_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('momentum_stage', sa.String(length=32), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("momentum_stage IN ('EARLY', 'ACCELERATING', 'TRENDING', 'OVERHEATED', 'DECLINING')", name='ck_momentum_stage'),
    sa.CheckConstraint('momentum_score >= 0 AND momentum_score <= 100', name='ck_momentum_score'),
    sa.CheckConstraint('volatility_score >= 0 AND volatility_score <= 100', name='ck_momentum_volatility'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'calculated_at', name='uq_momentum_calculated')
    )
    op.create_index('ix_momentum_rank', 'momentum_metrics', ['momentum_score', 'calculated_at'], unique=False)
    op.create_index('ix_momentum_token_calculated', 'momentum_metrics', ['token_id', 'calculated_at'], unique=False)
    op.create_table('opportunity_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('growth_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('liquidity_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('adoption_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('opportunity_tier', sa.String(length=32), nullable=False),
    sa.Column('supporting_data_json', sa.JSON(), nullable=False),
    sa.Column('event_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("opportunity_tier IN ('EXCEPTIONAL_OPPORTUNITY', 'STRONG_OPPORTUNITY', 'WATCHLIST')", name='ck_opportunity_tier'),
    sa.CheckConstraint('adoption_score >= 0 AND adoption_score <= 100', name='ck_opportunity_adoption'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_opportunity_confidence'),
    sa.CheckConstraint('growth_score >= 0 AND growth_score <= 100', name='ck_opportunity_growth'),
    sa.CheckConstraint('liquidity_score >= 0 AND liquidity_score <= 100', name='ck_opportunity_liquidity'),
    sa.CheckConstraint('momentum_score >= 0 AND momentum_score <= 100', name='ck_opportunity_momentum'),
    sa.CheckConstraint('signal_strength >= 0 AND signal_strength <= 100', name='ck_opportunity_strength'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_fingerprint')
    )
    op.create_index('ix_opportunity_rank', 'opportunity_signals', ['signal_strength', 'created_at'], unique=False)
    op.create_index(op.f('ix_opportunity_signals_opportunity_tier'), 'opportunity_signals', ['opportunity_tier'], unique=False)
    op.create_index('ix_opportunity_token_created', 'opportunity_signals', ['token_id', 'created_at'], unique=False)
    op.create_table('token_growth_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('holder_count', sa.Integer(), nullable=False),
    sa.Column('holder_growth_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('holder_growth_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('transaction_growth_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('transaction_growth_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('volume_growth_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume_growth_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('market_cap_growth_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('market_cap_growth_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('liquidity_value', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('liquidity_growth_24h', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('liquidity_growth_7d', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'calculated_at', name='uq_token_growth_calculated')
    )
    op.create_index('ix_token_growth_calculated', 'token_growth_metrics', ['calculated_at'], unique=False)
    op.create_index('ix_token_growth_token_calculated', 'token_growth_metrics', ['token_id', 'calculated_at'], unique=False)
    op.add_column('price_history', sa.Column('liquidity_value', sa.Numeric(precision=38, scale=2), nullable=True))
    if op.get_bind().dialect.name == 'postgresql':
        for table in ('token_growth_metrics', 'momentum_metrics', 'opportunity_signals'):
            op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'liquidity_value')
    op.drop_index('ix_token_growth_token_calculated', table_name='token_growth_metrics')
    op.drop_index('ix_token_growth_calculated', table_name='token_growth_metrics')
    op.drop_table('token_growth_metrics')
    op.drop_index('ix_opportunity_token_created', table_name='opportunity_signals')
    op.drop_index(op.f('ix_opportunity_signals_opportunity_tier'), table_name='opportunity_signals')
    op.drop_index('ix_opportunity_rank', table_name='opportunity_signals')
    op.drop_table('opportunity_signals')
    op.drop_index('ix_momentum_token_calculated', table_name='momentum_metrics')
    op.drop_index('ix_momentum_rank', table_name='momentum_metrics')
    op.drop_table('momentum_metrics')
    # ### end Alembic commands ###
