"""add smart money intelligence

Revision ID: f9142beb610b
Revises: 3e493c08fa19
Create Date: 2026-06-20 12:06:48.469153
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9142beb610b'
down_revision: Union[str, None] = '3e493c08fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_money_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('number_of_smart_wallets', sa.Integer(), nullable=False),
    sa.Column('total_capital_moved', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('supporting_data_json', sa.JSON(), nullable=False),
    sa.Column('event_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.CheckConstraint('signal_strength >= 0 AND signal_strength <= 100', name='ck_smart_money_signals_strength'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_smart_money_signals_confidence'),
    sa.CheckConstraint("signal_type IN ('ELITE_ENTRY', 'ACCUMULATION', 'SMART_MONEY_CLUSTER', 'SMART_MONEY_EXIT')", name='ck_smart_money_signals_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_fingerprint')
    )
    op.create_index(op.f('ix_smart_money_signals_created_at'), 'smart_money_signals', ['created_at'], unique=False)
    op.create_index('ix_smart_money_signals_token_created', 'smart_money_signals', ['token_id', 'created_at'], unique=False)
    op.create_index('ix_smart_money_signals_type_created', 'smart_money_signals', ['signal_type', 'created_at'], unique=False)
    op.create_table('wallet_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_buys', sa.Integer(), nullable=False),
    sa.Column('total_sells', sa.Integer(), nullable=False),
    sa.Column('total_tokens_traded', sa.Integer(), nullable=False),
    sa.Column('last_processed_transaction_id', sa.Integer(), nullable=False),
    sa.Column('estimated_total_profit', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('estimated_roi_percentage', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_return_percentage', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_holding_time_days', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('loss_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('largest_winner_percentage', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('largest_loss_percentage', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.CheckConstraint('win_rate >= 0 AND win_rate <= 100', name='ck_wallet_metrics_win_rate'),
    sa.CheckConstraint('loss_rate >= 0 AND loss_rate <= 100', name='ck_wallet_metrics_loss_rate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_metrics_last_updated'), 'wallet_metrics', ['last_updated'], unique=False)
    op.create_index(op.f('ix_wallet_metrics_wallet_id'), 'wallet_metrics', ['wallet_id'], unique=True)
    op.create_table('wallet_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('total_bought_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('total_sold_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('realized_profit', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('unrealized_profit', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('first_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.CheckConstraint('current_balance >= 0', name='ck_wallet_positions_balance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'token_id', name='uq_wallet_position_wallet_token')
    )
    op.create_index(op.f('ix_wallet_positions_latest_activity_date'), 'wallet_positions', ['latest_activity_date'], unique=False)
    op.create_index('ix_wallet_positions_token_activity', 'wallet_positions', ['token_id', 'latest_activity_date'], unique=False)
    op.create_index('ix_wallet_positions_wallet_activity', 'wallet_positions', ['wallet_id', 'latest_activity_date'], unique=False)
    op.create_table('wallet_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('profitability_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('consistency_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('risk_management_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('recent_performance_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('final_smart_money_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('wallet_tier', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.CheckConstraint('final_smart_money_score >= 0 AND final_smart_money_score <= 100', name='ck_wallet_scores_final'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_wallet_scores_confidence'),
    sa.CheckConstraint("wallet_tier IN ('ELITE', 'ADVANCED', 'INTERMEDIATE', 'SPECULATIVE', 'LOW_QUALITY')", name='ck_wallet_scores_tier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_scores_calculated_at'), 'wallet_scores', ['calculated_at'], unique=False)
    op.create_index('ix_wallet_scores_rank', 'wallet_scores', ['final_smart_money_score', 'calculated_at'], unique=False)
    op.create_index('ix_wallet_scores_wallet_calculated', 'wallet_scores', ['wallet_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_wallet_scores_wallet_tier'), 'wallet_scores', ['wallet_tier'], unique=False)
    op.create_index('ix_transactions_wallet_token_timestamp', 'transactions', ['wallet_id', 'token_id', 'timestamp'], unique=False)
    op.create_index('ix_transactions_wallet_type_timestamp', 'transactions', ['wallet_id', 'transaction_type', 'timestamp'], unique=False)
    if op.get_bind().dialect.name == 'postgresql':
        for table in ('wallet_metrics', 'wallet_scores', 'wallet_positions', 'smart_money_signals'):
            op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_wallet_type_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_wallet_token_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_wallet_scores_wallet_tier'), table_name='wallet_scores')
    op.drop_index('ix_wallet_scores_wallet_calculated', table_name='wallet_scores')
    op.drop_index('ix_wallet_scores_rank', table_name='wallet_scores')
    op.drop_index(op.f('ix_wallet_scores_calculated_at'), table_name='wallet_scores')
    op.drop_table('wallet_scores')
    op.drop_index('ix_wallet_positions_wallet_activity', table_name='wallet_positions')
    op.drop_index('ix_wallet_positions_token_activity', table_name='wallet_positions')
    op.drop_index(op.f('ix_wallet_positions_latest_activity_date'), table_name='wallet_positions')
    op.drop_table('wallet_positions')
    op.drop_index(op.f('ix_wallet_metrics_wallet_id'), table_name='wallet_metrics')
    op.drop_index(op.f('ix_wallet_metrics_last_updated'), table_name='wallet_metrics')
    op.drop_table('wallet_metrics')
    op.drop_index('ix_smart_money_signals_type_created', table_name='smart_money_signals')
    op.drop_index('ix_smart_money_signals_token_created', table_name='smart_money_signals')
    op.drop_index(op.f('ix_smart_money_signals_created_at'), table_name='smart_money_signals')
    op.drop_table('smart_money_signals')
    # ### end Alembic commands ###
